run:
  skip-files:
    - 'schema.go'
linters:
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - goconst
    - golint
    - gofmt
    - gosec
    - govet
    - ineffassign
    - interfacer
    - lll
    - megacheck
    - nakedret
    - structcheck
    - unconvert
    - varcheck
