[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "e772aac3c17747e529dae4bcb36f1b82539414df"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "0cdc28c3cfb52f3f3d9bd380ace4342db0782a96"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-azurerm"
  version = "=1.6.0"

[[override]]
  name = "github.com/pulumi/terraform"
  branch = "pulumi-master"
