[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "7e14a09b3b63bfab1aaeac47fdad944ac466b241"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "master"

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=1.12.32"

[[override]]
  name = "github.com/hashicorp/terraform"
  source = "github.com/pulumi/terraform"
  branch = "pulumi-master"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-azurerm"
  version = "=1.0.1"
