[[override]]
  name = "github.com/pulumi/pulumi"
  branch = "release/0.12"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "release/0.12"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-azurerm"
  version = "=1.3.1"

[[override]]
  name = "github.com/pulumi/terraform"
  branch = "pulumi-master"
