[[constraint]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[constraint]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "master"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-azurerm"
  version = "=1.6.0"

[[override]]
  name = "github.com/pulumi/terraform"
  branch = "pulumi-master"
