[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "7e14a09b3b63bfab1aaeac47fdad944ac466b241"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-azurerm"
  version = "=1.3.1"
  
[[override]]
  name = "github.com/pulumi/terraform"
  branch = "pulumi-master"
