[[override]]
  name = "github.com/pulumi/pulumi"
  version = "v0.12.2"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "634b892f62c1d63393d1c092fac350776e9e4a91"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-azurerm"
  version = "=1.6.0"

[[override]]
  name = "github.com/pulumi/terraform"
  branch = "pulumi-master"
